### ISSUE TITLE
请问我的免费开源工具哪里让您觉得低价值了？

### ISSUE THREAD

**Issue by ausdruck** [cnvaan/Google-Chinese-Results-Blocklist#1]
浏览了下您的黑名单，其中大约 1% 的网站主体都是我独立开发的程序，请说下遇到的问题，我现在就改源码。 https://github.com/ausdruck/linxphp

**Comment by cnvaan** [comment]
你好，请问能麻烦列出几个认为不该屏蔽的网站链接吗？

**Comment by ausdruck** [comment]
都开源了4年，对于大部分放我源码的网站早就失控了，但作为发明人我觉得理所当然要改进，譬如我个人网站你觉得什么漏洞需要直接屏蔽？ https://www.weixingon.com/

**Comment by cnvaan** [comment]
不好意思，该网站太 spam 了……

**Comment by ausdruck** [comment]
明白了，程序自动生成的标题来自百度下拉提示词，摘要来自百度百科，主体内容来自百度搜索结果，相关词来自百度相关搜索词，所以太垃圾。不过百度替换成谷歌，直接触犯法律，没法改。
